import { ArrowUpRight, ArrowRight, ClipboardList, ShieldCheck, Wrench, Boxes, Check } from 'lucide-react';

export default function Home() {
 return <main id="top">
  <header className="nav wrap"><a className="wordmark" href="#top" aria-label="Xplormate home"><span className="brand-mark">✳</span>xplormate<span className="brand-period">.</span></a><nav aria-label="Main navigation"><a href="#opportunities">Opportunities</a><a href="#approach">Our approach</a><a className="nav-cta" href="#contact">Let’s talk <ArrowUpRight size={17}/></a></nav></header>
  <section className="hero wrap"><div className="eyebrow"><span className="eyebrow-line"/> AI TRANSFORMATION FOR MANUFACTURING</div><h1>Your factory runs<br/>on processes.<br/><span>Too much still runs<br className="desktop-break"/> on follow-ups.</span></h1><div className="hero-bottom"><p>Bring AI into the work between your systems.<br className="desktop-break"/> Start with the updates, handovers, and open issues<br className="desktop-break"/> your team spends its day chasing.</p><a className="button primary" href="#contact">Find your first AI opportunity <ArrowUpRight size={21}/></a></div><div className="hero-foot"><span>PRODUCTION / QUALITY / MAINTENANCE / MATERIALS</span><a href="#opportunities">Explore the possibilities <ArrowRight size={16}/></a></div></section>
  <section className="light-section" id="opportunities"><div className="wrap opportunities">
   <div className="section-label">01 / WHERE TO START</div>
   <div className="section-heading"><h2>The next improvement<br/>is hiding in the follow-up.</h2><p>Your systems hold the records. Your people connect the dots. Explore where AI could help with the coordination work in between.</p></div>
   <div className="opportunity-grid">
    {[
     {icon:ClipboardList,n:'01',title:'Production follow-ups',pain:'“Where are we on this order?”',body:'Bring scattered updates into a clearer picture of progress, blockers, and the next action.',measure:'Time spent chasing status'},
     {icon:ShieldCheck,n:'02',title:'Quality issue closure',pain:'“Who is closing this issue?”',body:'Turn an issue report into an accountable follow-up, with an owner, a due date, and evidence of closure.',measure:'Time from issue to verified closure'},
     {icon:Wrench,n:'03',title:'Maintenance coordination',pain:'“Did the next shift pick this up?”',body:'Carry open issues, maintenance requests, and decisions across shifts with the context intact.',measure:'Unresolved handovers and repeat follow-ups'},
     {icon:Boxes,n:'04',title:'Material readiness',pain:'“What could hold up tomorrow’s plan?”',body:'Surface missing updates and potential shortages so the right person can investigate before production is affected.',measure:'Time to identify and act on a blocker'}
    ].map(item=><article className="opportunity" key={item.n}><div className="card-top"><item.icon size={25} strokeWidth={1.4}/><span>{item.n}</span></div><h3>{item.title}</h3><p className="pain">{item.pain}</p><p>{item.body}</p><div className="measure"><span>POSSIBLE SUCCESS MEASURE</span>{item.measure}</div></article>)}
   </div><p className="caption">Illustrative opportunities to assess together. Scope and feasibility depend on your workflow, systems, and data.</p>
  </div></section>
  <section className="workflow wrap"><div className="section-label">02 / FROM SIGNAL TO CLOSURE</div><div className="section-heading"><h2>An update should lead<br/>to something happening.</h2><p>Visibility is a start. The useful question is what happens next, who owns it, and how you know it is done.</p></div>
   <div className="example-label"><span>ILLUSTRATIVE WORKFLOW</span><span>A material shortage before the next shift</span></div>
   <div className="flow-grid">
    <article><div className="flow-number">01 <ArrowRight size={19}/></div><h3>Signal</h3><p>A planner flags that a required part has not arrived.</p><span className="flow-tag">Capture the context</span></article>
    <article><div className="flow-number">02 <ArrowRight size={19}/></div><h3>Owner</h3><p>The buyer receives the issue with the affected order and timing.</p><span className="flow-tag">Make responsibility clear</span></article>
    <article><div className="flow-number">03 <ArrowRight size={19}/></div><h3>Action</h3><p>AI could organise the updates and draft a follow-up for review.</p><span className="flow-tag">Support the next step</span></article>
    <article><div className="flow-number">04 <Check size={19}/></div><h3>Closure</h3><p>The responsible person confirms receipt and updates the plan.</p><span className="flow-tag">Verify the outcome</span></article>
   </div><div className="workflow-note"><ShieldCheck size={21}/><p>People approve consequential decisions. A proposed workflow must define what AI can do, when to escalate, and who signs off.</p></div>
  </section>
  <section className="light-section" id="approach"><div className="wrap approach"><div className="section-label">03 / OUR APPROACH</div><div className="approach-layout"><div className="approach-intro"><h2>Start with the work.<br/>Make AI earn<br/>its place.</h2><p>We’re speaking with manufacturing teams to understand where coordination breaks down and where AI could make a measurable difference.</p><a className="text-link" href="#contact">Explore a workflow with us <ArrowUpRight size={18}/></a></div><div className="steps">
   <article><span>01</span><div><h3>Understand what actually happens</h3><p>Walk through a recent example: the trigger, the people involved, the systems used, and the point where work got stuck.</p><small>START WITH A REAL WORKFLOW</small></div></article>
   <article><span>02</span><div><h3>Find a worthwhile intervention</h3><p>Identify a specific task AI could support. Check data access, exceptions, human review, and whether simpler changes would solve the problem.</p><small>AGREE ON THE PROBLEM AND THE BASELINE</small></div></article>
   <article><span>03</span><div><h3>Scope a focused pilot</h3><p>If there is a fit, define the boundaries, responsibilities, cost, and success measure before making a delivery commitment.</p><small>DECIDE WHAT WOULD MAKE IT WORTHWHILE</small></div></article>
  </div></div></div></section>
  <section className="faq wrap" id="questions"><div><div className="section-label">04 / A FEW PRACTICAL QUESTIONS</div><h2>Before we talk.</h2><p>Clear expectations from<br/>the first conversation.</p></div><div className="faq-items">
   {[
    ['Is Xplormate a ready-to-use software product?','Xplormate is at the discovery stage. We’re exploring AI transformation with manufacturing teams, starting with specific operating problems. An initial conversation is about understanding your workflow and assessing fit; it is not a demonstration of a finished platform.'],
    ['Do we need to replace our ERP or MES?','Replacing a core system is not the starting assumption. We first look at the coordination around your current tools. Any proposed connection to an ERP, MES, spreadsheet, or messaging system would need a separate feasibility and access review.'],
    ['What if our data is scattered or incomplete?','That is useful to understand early. We can discuss what information exists, where it lives, and who owns it. Some workflows may need better records or a simpler process before AI would be useful.'],
    ['Will AI make decisions on its own?','The appropriate level of autonomy depends on the task and its consequences. Any pilot should explicitly define human approvals, exception handling, access limits, and a way to review what happened.'],
    ['Can you share case studies or guaranteed savings?','We do not yet have customer case studies to share. The examples on this page illustrate potential workflows, not delivered results. Savings, scope, and timelines would need to be assessed against your operation.'],
    ['What should I bring to the first conversation?','One recent example of work getting delayed or repeatedly chased is enough to start. Describe the people, tools, and handoffs involved. There is no need to share confidential production data or documents in an introductory LinkedIn message.']
   ].map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}
  </div></section>
  <section className="contact wrap" id="contact"><div className="section-label">LET’S START WITH YOUR OPERATION</div><h2>What is your team<br/><span>still chasing?</span></h2><p>Start with one recurring bottleneck. Let’s map what happens today, explore where AI might help, and see whether there is a sensible next step.</p><a className="button primary" href="https://www.linkedin.com/in/jeetendra-yadav-4363457a/" target="_blank" rel="noopener noreferrer">Talk to Jeetu on LinkedIn <ArrowUpRight size={21}/></a><small>Connect or message Jeetu on LinkedIn. Mention the workflow you want to improve.</small><div className="conversation-prompt"><span>A SIMPLE WAY TO START</span><p>“We spend a lot of time following up on ___. Today, we handle it through ___. I’d like to explore a better way.”</p></div></section>
  <footer className="wrap"><a className="wordmark" href="#top">xplormate.</a><span>AI transformation for manufacturing operations.</span><a href="https://www.linkedin.com/company/xplormate/" target="_blank" rel="noopener noreferrer">LinkedIn <ArrowUpRight size={16}/></a></footer>
 </main>
}
